### ISSUE TITLE
Facebook Connect on Android is not working - HttpResponseException): Bad Request

### ISSUE THREAD

**Issue by gregorifaroux** [aaronksaunders/TiParseTestApp#2]
Hi,

The TestApp works very well on iOS, but on Android I receive the following error message:
[ERROR] :  TiHttpClient: (TiHttpClient-1) [29162,29405] HTTP Error (org.apache.http.client.HttpResponseException): Bad Request
[ERROR] :  TiHttpClient: org.apache.http.client.HttpResponseException: Bad Request
[ERROR] :  TiHttpClient:    at ti.modules.titanium.network.TiHTTPClient$LocalResponseHandler.handleResponse(TiHTTPClient.java:258)
[ERROR] :  TiHttpClient:    at ti.modules.titanium.network.TiHTTPClient$LocalResponseHandler.handleResponse(TiHTTPClient.java:217)
[ERROR] :  TiHttpClient:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:657)
[ERROR] :  TiHttpClient:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:637)
[ERROR] :  TiHttpClient:    at ti.modules.titanium.network.TiHTTPClient$ClientRunnable.run(TiHTTPClient.java:1287)
[ERROR] :  TiHttpClient:    at java.lang.Thread.run(Thread.java:856)

Any ideas!?
Thanks,
Gregori

**Comment by aaronksaunders** [comment]
Did you follow the appceleratoe instructions for setting up Facebook and configure the app properly in the Facebook developers app conaile

**Comment by gregorifaroux** [comment]
Yes, it is working well with iOS. On your app example and my app, the facebook login and TiParse work like a charm. On Android, I get that error. Could you please confirm that the facebook connect works on Android on your side? Then, I would know it's on my side, not TiParse. Thanks.

**Comment by gregorifaroux** [comment]
Here are some additional info on the error I receive on Android (but not on iOS)... error 401 unauthorized. No idea yet on where there is a difference of behavior between the two

{"password":null,"status":401,"username":null,"autoRedirect":true,"bubbleParent":true,"allResponseHeaders":"Access-Control-Allow-Origin:_\nAccess-Control-Request-Method:_\nCache-Control:no-cache\nContent-Type:application/json; charset=utf-8\nDate:Fri, 06 Jun 2014 16:49:51 GMT\nServer:nginx/1.4.4\nSet-Cookie:_parse_session=BAh7BkkiD3Nlc3Npb25faWQGOgZFRiIlMWZmODkxNmUwN2Y4NzYxNjc1MzA0NzU5MWM1ZDljZGU%3D--af9c89785f5081e9e9fdfb8bf143f180786e8d7e; domain=.parse.com; path=/; expires=Sun, 06-Jul-2014 16:49:51 GMT; secure; HttpOnly\nStatus:401 Unauthorized\nWWW-Authenticate:Basic realm=\"Parse\"\nX-Content-Type-Options:nosniff\nX-Runtime:0.009385\nX-UA-Compatible:IE=Edge,chrome=1\nContent-Length:24\nConnection:keep-alive\n","location":"https://api.parse.com/1/users","timeout":5000,"autoEncodeUrl":true,"apiName":"Ti.Network.HTTPClient","responseXML":null,"validatesSecureCertificate":false,"readyState":3,"domain":null,"responseText":"{\"error\":\"unauthorized\"}","responseData":null,"connectionType":"POST","statusText":"Unauthorized","connected":true,"_events":{"disposehandle":{}}}

**Comment by aaronksaunders** [comment]
i started to investigate the issue and will update you, I am seeing the same problem

**Comment by gregorifaroux** [comment]
I do not know if that helps but I tried the following with no luck based on what I found on Internet:
. autourlencode: false 
. commented out the set content-type for Android
. try the onload / onerror as it behaves differently between iOS and Android :
   var xhr_response = function() {
    Ti.API.error("GFA GFA: "+JSON.stringify(xhr));
      if (4 === xhr.readyState) {
        if (handled)
          return;
        handled = !0;
        if (xhr.status >= 200 && 300 > xhr.status) {
          var response;
          try {
            response = JSON.parse(xhr.responseText);
          } catch (e) {
            promise.reject(e);
          }
          response && promise.resolve(response, xhr.status, xhr);
        } else
          promise.reject(xhr);
      }
    };

```
xhr.onerror = xhr_response;
xhr.onload = xhr_response;
```

**Comment by adampash** [comment]
Fwiw, I've just run into a similar problem using TiParse. I'm not using the Facebook portion, but when I try to run Cloud Code from Android (`Parse.Cloud.run('createSomething', params, callbacks...)`), I run into the same errors in my console. Let me know if there's any information that might help get to the bottom of it!

**Comment by gregorifaroux** [comment]
I just tested with the latest SDK... 3.4 for Appcelerator and 1.3 for Parse Javascript... works fine on iOS, but still no luck w/ Android:
[ERROR] :  TiHttpClient: (TiHttpClient-2) [43119,77484] HTTP Error (org.apache.http.client.HttpResponseException): Bad Request

 {"password":null,"status":400,"autoRedirect":true,"bubbleParent":true,"allResponseHeaders":"Access-Control-Allow-Origin:_\nAccess-Control-Request-Method:_\nCache-Control:no-cache\nContent-Type:application/json; charset=utf-8\nDate:Wed, 01 Oct 2014 16:00:24 GMT\nServer:nginx/1.6.0\nSet-Cookie:_parse_session=BAh7BkkiD3Nlc3Npb25faWQGOgZFRiIlNjE0NzFhNGNiZTQ3NjE1YTVmNmZmYmYzZGFlMzIyODQ%3D--5730c455bf22d522539abb342eb5a5057093d1e0; domain=.parse.com; path=/; expires=Fri, 31-Oct-2014 16:00:24 GMT; secure; HttpOnly\nStatus:400 Bad Request\nX-Content-Type-Options:nosniff\nX-Runtime:0.101458\nX-UA-Compatible:IE=Edge,chrome=1\nContent-Length:49\nConnection:keep-alive\n","responseData":null,"location":"https://api.parse.com/1/users","timeout":5000,"autoEncodeUrl":true,"apiName":"Ti.Network.HTTPClient","responseXML":null,"validatesSecureCertificate":false,"readyState":3,"domain":null,"responseText":"{\"code\":251,\"error\":\"Parse::InvalidSessionError\"}","username":null,"connectionType":"POST","statusText":"Bad Request","connected":true,"_events":{"disposehandle":{}}}

**Comment by tahara-san** [comment]
I forgot which line the problem comes from but it's because titanium android httpclient throws exception whenever it receives status codes that are beyond certain value (it's 300 or something), resulting in not proceeding to ready state 3 or 4, and it gets stuck at readyState 2.

It won't get rid of the "Bad Request" warning in the console but you can take a walk around by modifying ti.parse_mine.js like this one:

```
// ti.parse_mine.js @ line 151
  Parse._ajax = function(method, url, data, success, error) {

    var options = {
      success : success,
      error : error
    };

    var promise = new Parse.Promise();
    var handled = !1;
    var xhr = Ti.Network.createHTTPClient({
      autoEncodeUrl:false,
      timeout : 5000
    });

    // use this code block if you want to see readyState changes
    //
    // xhr.onreadystatechange = function(){
        // Ti.API.info("readyState --> " + xhr.readyState);
    // };

    xhr.onload = function() {
        Ti.API.info("xhr.onload invoked, request successful:::");
        if (handled) {
            return;
        }
        handled = !0;
        if (this.status >= 200 && 300 > this.status) {
            var response;
            try {
                response = eval('('+this.responseText+')');
            } catch (e) {
                promise.reject(e);
            }
            response && promise.resolve(response, this.status, this);
        } else {
            promise.reject(this);
        }
    };

    xhr.onerror = function(){
        Ti.API.info("xhr.onerror invoked, request failed, and promise rejected:::");
        promise.reject(this);
    };

    /*
     * 
     *  ORIGINAL SOURCE BELOW: it works on iOS but not on android since readyState wont change 3-4.
     * 
     */
    // xhr.onreadystatechange = function() {
      // if (4 === xhr.readyState) {
        // if (handled)
          // return;
        // handled = !0;
        // if (xhr.status >= 200 && 300 > xhr.status) {
          // var response;
          // try {
            // response = JSON.parse(xhr.responseText);
          // } catch (e) {
            // promise.reject(e);
          // }
          // response && promise.resolve(response, xhr.status, xhr);
        // } else
          // promise.reject(xhr);
      // }
    // };

    xhr.open(method, url, !0);
    xhr.setRequestHeader("Content-Type", "text/plain");
    xhr.send(data);
    return promise._thenRunCallbacks(options);
  };
```

I've tested it with Ti 3.2.3GA and Ti 3.3.0GA, with android 4.2, 4.4.2, 4.4.4. 
Everything's working awesome so far, including parse analytics and push notifications.
(push notification requires other modules and REST API calls to parse though.)

As to facebook login, I'm gonna work on it today :)

**Comment by tahara-san** [comment]
Guess I got it to work, with modding ti.parse_mine.js a bit again.

```
// ti.parse_mine.js @ around line 60 (inside FB.provider.authenticate)
            if (options.success) {
                options.success(self, {
                    id :  response.data.id,
                    access_token : TiFacebook.accessToken,
                    expiration_date : (new Date(TiFacebook.expirationDate)).toJSON()
              });
```

to

```
// ti.parse_mine.js @ around line 60 (inside FB.provider.authenticate)
            if (options.success) {
                options.success(self, {
                    id :  JSON.parse(response.data).id,
                    access_token : TiFacebook.accessToken,
                    expiration_date : (new Date(TiFacebook.expirationDate)).toJSON()
              });
```

Without this fix you'll get:

```
[ERROR] XMLModule: (KrollRuntimeThread) [33,122745] Error parsing XML
```

with returned error:

```
{code:251,error:"Parse::InvalidSessionError"}
```

I've tested it on Ti3.3.0GA, Ti.Facebook 3.0.2 with android 4.4.2 actual device.
Hope that helps you!

**Comment by gregorifaroux** [comment]
Thank you so much! The facebook login works on Android thanks to your mods of tiparse. I will continue testing with our full app, but so far so good. It will help me indeed.

**Comment by aaronksaunders** [comment]
@gregorifaroux @tahara-san thanks for tracking this down, if you submit a pull request I will make the edits

**Comment by tahara-san** [comment]
@aaronksaunders will send it once I test it on iOS, thanks for sharing awesome module Aaron!

**Comment by gregorifaroux** [comment]
@aaronksaunders @tahara-san I created a pull request that is tested on Android and iOS for the facebook login. I added some tweaks to make it work on both. That version includes the latest Titanium SDK 3.4 and Parse 1.3.0. Feel free to use or ignore if @tahara-san comes with a better version.

Thanks to both of you for the great work.

**Comment by tahara-san** [comment]
@gregorifaroux thanks man, I've not checked on yours deeply yet but you might want to remove your app key and rest-api key right away.

**Comment by gregorifaroux** [comment]
@tahara-san Thanks; done. The main tweak is for iOS, the response.data.id worked without the JSON.parse, so I did something like this:
                id : Alloy.Globals.isAndroid?JSON.parse(response.data).id:response.data.id,
The other changes were about the android app closing after successful facebook login.

**Comment by nitrag** [comment]
Needed this to fix 3.5.2 SDK issues on iOS too. Thanks all!

**Comment by torlanco** [comment]
I am getting the following error in Titanium SDK 5.0.2.GA

```[ERROR] :  LiferayBeaconsModule: (KrollRuntimeThread) [1,272802] Cannot start monitoring region {major=53376, identifier=iBeacon1, minor=40477, uuid=B9407F30-F5F8-466E-AFF9-25556B57FE6D}
[ERROR] :  LiferayBeaconsModule: android.os.RemoteException: The IBeaconManager is not bound to the service.  Call iBeaconManager.bind(IBeaconConsumer consumer) and wait for a callback to onIBeaconServiceConnect()
[ERROR] :  LiferayBeaconsModule: 	at com.radiusnetworks.ibeacon.IBeaconManager.startMonitoringBeaconsInRegion(IBeaconManager.java:440)
[ERROR] :  LiferayBeaconsModule: 	at com.liferay.beacons.LiferayBeaconsModule.startMonitoringForRegion(LiferayBeaconsModule.java:196)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:73)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1145)
[ERROR] :  LiferayBeaconsModule: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  LiferayBeaconsModule: 	at android.os.Looper.loop(Looper.java:155)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[ERROR] :  LiferayBeaconsModule: (KrollRuntimeThread) [0,272808] Cannot start monitoring region {major=6517, identifier=iBeacon2, minor=22517, uuid=8492E75F-4FD6-469D-B132-043FE94921D8}
[ERROR] :  LiferayBeaconsModule: android.os.RemoteException: The IBeaconManager is not bound to the service.  Call iBeaconManager.bind(IBeaconConsumer consumer) and wait for a callback to onIBeaconServiceConnect()
[ERROR] :  LiferayBeaconsModule: 	at com.radiusnetworks.ibeacon.IBeaconManager.startMonitoringBeaconsInRegion(IBeaconManager.java:440)
[ERROR] :  LiferayBeaconsModule: 	at com.liferay.beacons.LiferayBeaconsModule.startMonitoringForRegion(LiferayBeaconsModule.java:196)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:73)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1145)
[ERROR] :  LiferayBeaconsModule: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  LiferayBeaconsModule: 	at android.os.Looper.loop(Looper.java:155)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[ERROR] :  LiferayBeaconsModule: (KrollRuntimeThread) [1,272813] Cannot start monitoring region {major=6518, identifier=iBeacon3, minor=22518, uuid=8492E75F-4FD6-469D-B132-043FE94921D8}
[ERROR] :  LiferayBeaconsModule: android.os.RemoteException: The IBeaconManager is not bound to the service.  Call iBeaconManager.bind(IBeaconConsumer consumer) and wait for a callback to onIBeaconServiceConnect()
[ERROR] :  LiferayBeaconsModule: 	at com.radiusnetworks.ibeacon.IBeaconManager.startMonitoringBeaconsInRegion(IBeaconManager.java:440)
[ERROR] :  LiferayBeaconsModule: 	at com.liferay.beacons.LiferayBeaconsModule.startMonitoringForRegion(LiferayBeaconsModule.java:196)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:73)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1145)
[ERROR] :  LiferayBeaconsModule: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  LiferayBeaconsModule: 	at android.os.Looper.loop(Looper.java:155)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[ERROR] :  LiferayBeaconsModule: (KrollRuntimeThread) [1,272818] Cannot start monitoring region {major=6519, identifier=iBeacon4, minor=22519, uuid=8492E75F-4FD6-469D-B132-043FE94921D8}
[ERROR] :  LiferayBeaconsModule: android.os.RemoteException: The IBeaconManager is not bound to the service.  Call iBeaconManager.bind(IBeaconConsumer consumer) and wait for a callback to onIBeaconServiceConnect()
[ERROR] :  LiferayBeaconsModule: 	at com.radiusnetworks.ibeacon.IBeaconManager.startMonitoringBeaconsInRegion(IBeaconManager.java:440)
[ERROR] :  LiferayBeaconsModule: 	at com.liferay.beacons.LiferayBeaconsModule.startMonitoringForRegion(LiferayBeaconsModule.java:196)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:73)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1145)
[ERROR] :  LiferayBeaconsModule: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  LiferayBeaconsModule: 	at android.os.Looper.loop(Looper.java:155)
[ERROR] :  LiferayBeaconsModule: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)```

My tiapp.xml looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<ti:app xmlns:ti="http://ti.appcelerator.org">
    <id>com.mlstudio.prego</id>
    <name>Chef Prego</name>
    <version>1.0</version>
    <publisher>torlanco</publisher>
    <url>https://www.facebook.com/PregoPR</url>
    <description>undefined</description>
    <copyright>2015 by torlanco</copyright>
    <icon>defaulticon.png</icon>
    <fullscreen>false</fullscreen>
    <navbar-hidden>false</navbar-hidden>
    <analytics>true</analytics>
    <guid>4042b5de-412f-44ac-9000-132382f49197</guid>
    <property name="ti.ui.defaultunit" type="string">dp</property>
    <android xmlns:android="http://schemas.android.com/apk/res/android">
        <manifest android:versionCode="2" android:versionName="0.6" package="com.mlstudio.prego">
            <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="21"/>
			<uses-permission android:name="android.permission.BLUETOOTH"/>
			<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
			
            <application android:theme="@style/Theme.Titanium">
				<service android:enabled="true"
				  android:exported="true"
				  android:isolatedProcess="false"
				  android:label="iBeacon"
				  android:name="com.radiusnetworks.ibeacon.service.IBeaconService">
				</service>
				<service android:enabled="true" android:name="com.radiusnetworks.ibeacon.IBeaconIntentProcessor">
				  <meta-data android:name="background" android:value="true" />
				  <intent-filter android:priority="1" >
					<action android:name="com.mlstudio.prego.DID_RANGING"/>
					<action android:name="com.mlstudio.prego.DID_MONITORING"/>
				  </intent-filter>
				</service>
              <activity
                  android:configChanges="keyboard|orientation|screenSize"
                  android:label="@string/app_name"
                  android:screenOrientation="portrait"
                  android:theme="@style/Theme.Titanium" android:windowSoftInputMode="stateAlwaysVisible">
                  <intent-filter>
                      <action android:name="android.intent.action.MAIN"/>
                      <category android:name="android.intent.category.LAUNCHER"/>
                  </intent-filter>
              </activity>
              <activity
                  android:configChanges="keyboard|orientation|screenSize"
                  android:name="org.appcelerator.titanium.TiActivity" android:screenOrientation="portrait"/>
              <activity
                  android:configChanges="keyboard|orientation|screenSize"
                  android:name="org.appcelerator.titanium.TiTranslucentActivity"
                  android:screenOrientation="portrait" android:theme="@style/Theme.AppCompat.Translucent"/>
              <activity android:configChanges="screenSize"
                  android:name="ti.modules.titanium.ui.android.TiPreferencesActivity" android:screenOrientation="portrait"/>
              <activity
                  android:configChanges="keyboard|orientation|screenSize"
                  android:name="ti.modules.titanium.media.TiCameraActivity"
                  android:screenOrientation="portrait" android:theme="@style/Theme.AppCompat.Translucent.NoTitleBar.Fullscreen"/>
              <service android:exported="false" android:name="com.appcelerator.analytics.APSAnalyticsService"/>
              <activity android:label="@string/app_name" android:name="com.facebook.LoginActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar"/>
              <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
            </application>

        </manifest>
    </android>
    <mobileweb>
        <precache/>
        <splash>
            <enabled>true</enabled>
            <inline-css-images>true</inline-css-images>
        </splash>
        <theme>default</theme>
    </mobileweb>
    <modules>
        <module platform="android" version="4.0.5">facebook</module>
        <module platform="android">ti.map</module>
        <module platform="android" version="0.3">com.liferay.beacons</module>
    </modules>
    <deployment-targets>
        <target device="android">true</target>
        <target device="ipad">false</target>
        <target device="iphone">false</target>
        <target device="mobileweb">false</target>
        <target device="windows">false</target>
    </deployment-targets>
    <sdk-version>5.0.2.GA</sdk-version>
    <plugins>
        <plugin version="1.0">ti.alloy</plugin>
    </plugins>
    <property name="appc-app-id" type="string">5612df0bf96eaa1a65d3949e</property>
</ti:app>
```
